alocadorOnline/alocador/urls.py
from django.conf.urls import url

from . import views

app_name = "alocador"

urlpatterns = [
    url(r'^$', views.index, name="index"),
    
    
    url(r'^(?P<user_id>[0-9]+)/resultado',views.resultado, name="resultado"),
    url(r'^(?P<user_id>[0-9]+)/avaliar', views.avaliarEquipe, name='avaliar'),
    url(r'^(?P<user_id>[0-9]+)/comparar',views.comparar,name="comparar"),
    url(r'^(?P<user_id>[0-9]+)/escolher', views.escolherAlocacao,name="escolher"),
    url(r'^(?P<user_id>[0-9]+)/alocar',views.alocarComAG,name="alocar"),
    url(r'^(?P<user_id>[0-9]+)/avUsuario',views.avaliar,name="avUsuario"),
    url(r'^(?P<user_id>[0-9]+)/testar',views.paramTeste,name="testar"),
    url(r'^(?P<user_id>[0-9]+)/salvarDados',views.salvarResultado,name="salvarDados"),
    url(r'^(?P<user_id>[0-9]+)/logout', views.logout,name='logout'),
    url(r'^resultado', views.gerarResultados, name='verificarResultados'),
    
    #apis
    url(r'^(?P<user_id>[0-9]+)/userinfo',views.informacoesDoUsuario, name="userinfo"),
    url(r'^(?P<user_id>[0-9]+)/menu',views.menu, name="menu"),
    url(r'cadastro/$',views.cadastro,name="cadastro"),  
    url(r'login_init/$',views.loginP,name="login_init"),
    url(r'login/$',views.login,name="login"),

    ]

alocadorOnline/alocadorOnline/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r"^alocador/", include("alocador.urls")),
    url(r'^admin/', admin.site.urls),
]

alocadorOnline/alocador/models.py
from django.db import models
from .ag.genetcAlgoritm import Cromossomo,DB
from .ag.comparador import avaliarDados

# Create your models here.

class Usuario(models.Model):
    nome = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    organizacao = models.CharField(max_length=200)
    senha = models.CharField(max_length=200)

class Alocacoes(models.Model):
    usuario = models.ForeignKey(Usuario,on_delete=models.CASCADE)
    cromossomo = models.CharField(max_length=200)
    analistas = models.IntegerField()
    arquitetos = models.IntegerField()
    programadores = models.IntegerField()
    testadores = models.IntegerField()
    ids = models.CharField(max_length=200)
    tempo = models.TimeField()
    Nafinidades = models.IntegerField()
    Nprodutividade = models.IntegerField()
    Nexperiencia = models.IntegerField()
    Ncusto = models.IntegerField()
    
    def getIds(self):
        return [int(i) for i in self.ids.split(",")]
    
    def cromoObject(self):
        CROMO = [int(i) for i in self.cromossomo.split(",")]
        IDS = [int(i) for i in self.ids.split(",")]
        equipe = Cromossomo(len(CROMO),IDS,[self.analistas,self.arquitetos,self.programadores,self.testadores],DB,CROMO)
        equipe.equipe = self.id
        return equipe
    

class Resultados(models.Model):
    alocacoes = models.ForeignKey(Alocacoes,on_delete=models.CASCADE)
    melhor_custo_beneficio = models.CharField(max_length=200)
    melhor_custo = models.CharField(max_length=200)
    melhor_afinidade = models.CharField(max_length=200)
    melhor_produtividade = models.CharField(max_length=200)
    melhor_experiencia = models.CharField(max_length=200)
    tempo = models.TimeField()
    
    def semelhancas(self):
        return avaliarDados(self.getAll,self.alocacoes.cromoObject())
    
    def cromoCustoBeneficio(self):
        CROMO = [int(i) for i in self.melhor_custo_beneficio.split(",")]
        equipe = Cromossomo(tamanho=len(CROMO),codificacao=[self.alocacoes.analistas,self.alocacoes.arquitetos,self.alocacoes.programadores,self.alocacoes.testadores],DB=DB,genes=CROMO)
        equipe.equipe = self.id
        return equipe
    
    def cromoCusto(self):
        CROMO = [int(i) for i in self.melhor_custo.split(",")]
        equipe = Cromossomo(tamanho=len(CROMO),codificacao=[self.alocacoes.analistas,self.alocacoes.arquitetos,self.alocacoes.programadores,self.alocacoes.testadores],DB=DB,genes=CROMO)
        equipe.equipe = self.id
        return equipe
    
    def cromoAfinidade(self):
        CROMO = [int(i) for i in self.melhor_afinidade.split(",")]
        equipe = Cromossomo(tamanho=len(CROMO),codificacao=[self.alocacoes.analistas,self.alocacoes.arquitetos,self.alocacoes.programadores,self.alocacoes.testadores],DB=DB,genes=CROMO)
        equipe.equipe = self.id
        return equipe
    
    def cromoProdutividade(self):
        CROMO = [int(i) for i in self.melhor_produtividade.split(",")]
        equipe = Cromossomo(tamanho=len(CROMO),codificacao=[self.alocacoes.analistas,self.alocacoes.arquitetos,self.alocacoes.programadores,self.alocacoes.testadores],DB=DB,genes=CROMO)
        equipe.equipe = self.id
        return equipe
    
    def cromoExperiencia(self):
        CROMO = [int(i) for i in self.melhor_experiencia.split(",")]
        equipe = Cromossomo(tamanho=len(CROMO),codificacao=[self.alocacoes.analistas,self.alocacoes.arquitetos,self.alocacoes.programadores,self.alocacoes.testadores],DB=DB,genes=CROMO)
        equipe.equipe = self.id
        return equipe
    @property
    def getAll(self):
        return [self.cromoCustoBeneficio(),self.cromoCusto(),self.cromoAfinidade(),self.cromoProdutividade(),self.cromoExperiencia()]

alocadorOnline/alocador/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponse
import os
from .ag.genetcAlgoritm import AG,Cromossomo,DB
from .ag import gerarteste,comparador
from alocador.models import Usuario,Alocacoes,Resultados
from django.utils.timezone import datetime
import random as r
import timeit
import numpy as np
import matplotlib
matplotlib.use('Agg')
from matplotlib import pyplot as plt
# Create your views here.

logado = dict()
ID = dict()

def autenticado(user_id):
    global logado
    print(len(logado))
    print(user_id)
    return user_id in logado

def idLogado(user_id):
    global logado
    return int(user_id)

def gerarChave(id):
    global logado, ID
    a =sum(r.sample(range(2000),20))
    if id in ID:
       if ID[id] in logado:
           del logado[ID[id]]
       del ID[id]
       
    if a in logado:
        return gerarChave(id)
    logado[a]=id
    ID[id]=a
    return id

def index(request):
    return render(request, 'alocador/index.html')

def loginP(request):
    return render(request, 'alocador/login.html')

def paramTeste(request,user_id):
    if autenticado(user_id):
        return render(request, 'alocador/index.html')
    return render(request, 'testes/inicio.html',{'id':user_id})

'''OK'''
def escolherAlocacao(request,user_id):
    if autenticado(user_id):
        return render(request, 'alocador/index.html')
    user = Usuario.objects.get(id=idLogado(user_id))
    alocacoes = Alocacoes.objects.filter(usuario=user)
    
    cromossomos = [i.cromoObject() for i in alocacoes]
    
    return render(request, 'testes/comparar.html', {'individuos':cromossomos,'id':user_id,'nome':user.nome})

def resultado(request,user_id):
    if autenticado(user_id):
        return render(request, 'alocador/index.html')
    try:
        analistas = int(request.POST['analistas'])
        arquitetos = int(request.POST['arquitetos'])
        programadores = int(request.POST['programadores'])
        testadores = int(request.POST['testadores'])
        geracoes = int(request.POST['geracoes'])
    except:
        return render(request, 'alocador/alocarWithAG.html',{
            'error_message':"todos os campos devem ser preenchidos",
            'id':user_id})
    if sum([analistas,arquitetos,programadores,testadores]) < 2:
        return render(request, 'alocador/alocarWithAG.html',{
            'error_message':"deve-se escolher no minimo 2 individuos para uma equipe",
            'id':user_id})
    ag = AG(nAnalistas_req=analistas,\
            nArquitetos_soft=arquitetos,\
            nProgramadores=programadores,\
            nTestadores=testadores,\
            max_geracao=geracoes)
    ag.ag()
    dados = ag.central(ag.pop.getDadosEstatisticos())
    melhores = ag.pop.retornarMelhores()
    return render(request, 'alocador/resultado.html', {
        'individuos': dados[:20],
        'id': user_id})

def alocarComAG(request,user_id):
    if autenticado(user_id):
        return render(request, 'alocador/index.html')
    return render(request, 'alocador/alocarWithAG.html',{'id':user_id})

"OK"   
def avaliarEquipe(request,user_id):
    if autenticado(user_id):
        return render(request, 'alocador/index.html')
    ind = tratarDados(request.POST['choice'])
    return render(request, 'alocador/detalhes.html', {"agentes": ind,"id":user_id})

def comparar(request,user_id):
    if autenticado(user_id):
        return render(request, 'alocador/index.html')
    ind = request.POST['choice']
    al = Alocacoes.objects.get(id=ind)
    ids = al.getIds()
    #print("geracoes",(20*len(ids))/5)
    ag = AG(nAnalistas_req=al.analistas,\
            nArquitetos_soft=al.arquitetos,\
            nProgramadores=al.programadores,\
            nTestadores=al.testadores,\
            max_geracao=5,\
            ids=ids)
    #((20*len(ids))/5)+60,\
    aginicio = timeit.default_timer()
    ag.ag()
    dados = [ag.central(ag.pop.getDadosEstatisticos())[0]]
    agfim = timeit.default_timer()
    resultado_tempo = int(agfim - aginicio)
    h = resultado_tempo // 60**2
    hmod = resultado_tempo % 60**2
    min = hmod // 60
    minmod = hmod % 60
    segundo = minmod 
    
    tempo = str(h)+ ":"+str(min)+":"+str(segundo)
    
    dados += ag.pop.retornarMelhores()
    valores = [str(i.genes)[1:-1] for i in dados]
    r = Resultados(alocacoes=al,\
                   tempo = tempo,\
                   melhor_custo_beneficio=valores[0],\
                   melhor_custo=valores[1],\
                   melhor_afinidade=valores[2],\
                   melhor_produtividade=valores[3],\
                   melhor_experiencia=valores[4])
    r.save()
    '''
    ob = al.cromoObject().objetivos
    v=0
    for i in dados:
        radar([ob]+[i.objetivos],v)
        v+=1
    #'''
    caminho = ["graficos/"+str(user_id)+"-1.JPEG","graficos/"+str(user_id)+"-2.JPEG","graficos/"+str(user_id)+"-3.JPEG","graficos/"+str(user_id)+"-4.JPEG","graficos/"+str(user_id)+"-5.JPEG"]
    radar(al.cromoObject().objetivos,[i.objetivos for i in dados],user_id)
    result = comparador.avaliarMassa(dados,al.cromoObject(),caminho)
    media = sum([i.resultado for i in result])/5
    #result.sort(key = lambda r: r.resultado,reverse=True)
    
    return render(request, 'testes/resultado.html', {"dados":result,"id":user_id,"media":media})

"OK"
def cadastro(request):
    try:
        nome = request.POST['nome']
        email = request.POST['email']
        emp = request.POST['organizacao']
        sen1 = request.POST['senha']
        sen2 = request.POST['senha2']
    except:
        return render(request, 'alocador/index.html',{'error_message': "Cadastro incompleto!"})
    if sen1 != sen2:
        return render(request, 'alocador/index.html',{'error_message': "As senhas nao sao iguais!"})
    
    user = Usuario(nome = nome, email = email, organizacao = emp, senha=sen1)
    user.save()
    
    user_id = gerarChave(user.id)
    
    return render(request, 'alocador/init.html',{'id': user_id})

def menu(request,user_id):
    if autenticado(user_id):
        return render(request, 'alocador/index.html')
    return render(request, 'alocador/init.html',{'id': user_id})
    
"OK"
def login(request):
    global logado
    try:
        nome = request.POST['nome']
        senha = request.POST['senha']
    except:
        return render(request, 'alocador/login.html',{'error_message': "Cadastro incompleto!"})
    
    try:
        user = Usuario.objects.get(nome=nome, senha=senha)
    except:
        return render(request, 'alocador/login.html',{'error_message': "senha ou usuario incorretos"})
    
    user_id = gerarChave(user.id)
    
    return render(request, 'alocador/init.html',{'id': user_id})

    
def logout(request,user_id):
    if not autenticado(user_id):
        return render(request, 'alocador/index.html')
    global logado,ID
    id = logado[int(user_id)]
    logado[int(user_id)] = None
    ID[id] = None
    print(logado.items())
    del id
    return render(request, 'alocador/index.html')


'''OK'''
def avaliar(request,user_id):
    if autenticado(user_id):
        return render(request, 'alocador/index.html')
    user = idLogado(user_id)
    try:
        result = dict(request.POST)
        result = dict([(i,result[i][0]) for i in result])
        
    except:
        return render(request, 'testes/inicio.html',{'id':user_id})
    gerarteste.gerarPagina(int(result['Nids']))
    result['id']=user_id
    return render(request, 'testes/pagina.html',result)

"OK"
def salvarResultado(request,user_id):
    if autenticado(user_id):
        return render(request, 'alocador/index.html')
    
    user = Usuario.objects.get(id=idLogado(user_id))
    result = dict(request.POST)
    result = dict([(i,result[i][0]) for i in result])
    
    alocacao = result['alocacao']
    tamanho = int(result['Nids'])
    analistas = int(result['analistas'])
    arquitetos = int(result['arquitetos'])
    programadores = int(result['programadores'])
    testadores = int(result['testadores'])
    IDs = result['IDs']
                
    afinidade = int(result['afinidade'])
    produtividade = int(result['produtividade'])
    experiencia = int(result['experiencia'])
    custo = int(result['custo'])
    
    tempo = result['horas']+":"+result['minutos']+":"+result['segundos']
    if len(alocacao) > 1 and len(alocacao.split(",")) == sum([analistas,arquitetos,programadores,testadores]) :
        alocado = Alocacoes(usuario=user,\
                            cromossomo=alocacao,\
                            analistas=analistas,\
                            arquitetos=arquitetos,\
                            programadores=programadores,\
                            testadores=testadores,\
                            ids=IDs,\
                            tempo=tempo,\
                            Nafinidades=afinidade,\
                            Nprodutividade=produtividade,\
                            Nexperiencia=experiencia,\
                            Ncusto=custo)#TODO:tirar s
        alocado.save()
        lista = [int(i) for i in alocacao.split(",")]
        ids = [int(i) for i in IDs.split(",")]
        equipe = Cromossomo(tamanho,ids,[analistas,arquitetos,programadores,testadores],DB,lista)
        return render(request, 'alocador/detalhes.html',{"agentes": equipe,"error_message": "alocacao N: "+str(alocado.id),"id" : user_id})
    return render(request, 'alocador/init.html', {"error_message": "ERRO !!!","id": user_id})


#TODO: gerar graficos
#TODO: resultados la do models
def informacoesDoUsuario(request,user_id):
    if autenticado(user_id):
        return render(request, 'alocador/index.html')
    
    user = Usuario.objects.get(id=idLogado(user_id))
    alocacoes = Alocacoes.objects.filter(usuario=user)
    dados = dict()
    dados["tempo"]= [0,0,0]
    dados["afinidade"]=0
    dados["produtividade"]=0
    dados["experiencia"]=0
    dados["custo"]=0
    dados["qtd"]=len(alocacoes)
    for i in alocacoes:
        dados["tempo"][0] += i.tempo.hour

alocadorOnline/alocador/templates/testes/0-comparar--modificado.html
<h1>Alocacoes realizadas por: {{ nome }} <a href="{% url 'alocador:logout' id %}">logout</a></h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'alocador:comparar' id %}" method="post">
{% csrf_token %}
{% for ind in individuos %}
	<label for="equipe:{{ forloop.counter }}">Equpe: {{ forloop.counter }}</label>
	<input type="radio" name="choice" id="choice" value="{{ ind.equipe }}" /><br />
    <label for="equipe:{{ forloop.counter }}">{{ ind.analistas }}</label><br />
    <label for="equipe:{{ forloop.counter }}">{{ ind.arquitetos }}</label><br />
    <label for="equipe:{{ forloop.counter }}">{{ ind.programadores }}</label><br />
    <label for="equipe:{{ forloop.counter }}">{{ ind.testadores }}</label><br />
    <label for="equipe:{{ forloop.counter }}">{{ ind.genes }}</label><br />
    <label for="equipe:{{ forloop.counter }}">media de afinidade:...... {{ ind.afinidade }}</label><br />
    <label for="equipe:{{ forloop.counter }}">media de custo:.......... {{ ind.custo }}</label><br />
    <label for="equipe:{{ forloop.counter }}">media de experiencia:.... {{ ind.experiencia }}</label><br />
    <label for="equipe:{{ forloop.counter }}">media de produtividade:.. {{ ind.produtividade }}</label><br /><br /><br />
{% endfor %}
<input type="submit" value="comparar equipe"/>
</form>

alocadorOnline/alocador/templates/testes/0-inicio--MODIFICADO.html
<h1>parametros do teste <a href="{% url 'alocador:logout' id %}">logout</a></h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'alocador:avUsuario' id %}" method="post">
{% csrf_token %}

<label>Numero de agentes: </label><input type="number" name="Nids" id="Nids" value=4/><br />
<label>analistas:..... </label><input type="number" name="analistas" id="analistas" value=1/><br />
<label>arquitetos:.... </label><input type="number" name="arquitetos" id="arquitetos" value=1/><br />
<label>programadores:. </label><input type="number" name="programadores" id="programadores" value=1/><br />
<label>testadores:.... </label><input type="number" name="testadores" id="testadores" value=1/><br />

<input type="submit" value="iniciar teste" />
</form>

alocadorOnline/alocador/templates/testes/comparar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>Contact V5</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1" %}'>
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href=' {% static "images/icons/favicon.ico" %}'/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href=' {% static "vendor/bootstrap/css/bootstrap.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href=' {% static "fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href=' {% static "fonts/iconic/css/material-design-iconic-font.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href=' {% static "vendor/animate/animate.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href=' {% static "vendor/css-hamburgers/hamburgers.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href=' {% static "vendor/animsition/css/animsition.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href=' {% static "vendor/select2/select2.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href=' {% static "vendor/daterangepicker/daterangepicker.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href=' {% static "vendor/noui/nouislider.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href=' {% static "css/util.css" %}'>
	<link rel="stylesheet" type="text/css" href=' {% static "css/main.css" %}'>
<!--===============================================================================================-->
</head>
<body>

	<div class="container-contact100">
		<div class="wrap-contact100">
			<form class="contact100-form validate-form" action="{% url 'alocador:comparar' id %}" method="post">
                {% csrf_token %}

                <a class="label-input100" href="{% url 'alocador:menu' id %}">Menu</a>
                <a class="label-input100" href="{% url 'alocador:logout' id %}">Sair</a>
                <span class="contact100-form-title">
					COMPARAR EQUIPE
				</span>
					<div class="wrap-contact100-form-radio">
						<span class="label-input100">alocações realizadas por você</span>
						{% for ind in individuos %}
							<div class="contact100-form-radio m-t-15">
								<input class="input-radio100" id="radio{{ ind.equipe }}" type="radio" name="choice" value="{{ ind.equipe }}" checked="checked">
								<label class="label-radio100" for="radio{{ ind.equipe }}">
									Equpe: {{ forloop.counter }}
								</label>
							</div>

								<span class="label-input100" for="equipe:{{ forloop.counter }}">{{ ind.analistas }}</span><br />
								<span class="label-input100" for="equipe:{{ forloop.counter }}">{{ ind.arquitetos }}</span><br />
								<span class="label-input100" for="equipe:{{ forloop.counter }}">{{ ind.programadores }}</span><br />
								<span class="label-input100" for="equipe:{{ forloop.counter }}">{{ ind.testadores }}</span><br />
								<span class="label-input100" for="equipe:{{ forloop.counter }}">{{ ind.genes }}</span><br />
								<table>
									<tr>
										<td><span class="label-input100" for="equipe:{{ forloop.counter }}">media de afinidade: </span></td>
										<td><span  class="label-input100">{{ ind.afinidade }}</span></td>
									</tr>
									<tr>
										<td><span class="label-input100" for="equipe:{{ forloop.counter }}">media de custo: </span></td>
										<td><span  class="label-input100">{{ ind.custo }}</span></td>
									</tr>
									<tr>
										<td><span class="label-input100" for="equipe:{{ forloop.counter }}">media de experiencia: </span></td>
										<td><span  class="label-input100">{{ ind.experiencia }}</span></td>
									</tr>
									<tr>
										<td width="86%"><span class="label-input100" for="equipe:{{ forloop.counter }}">media de produtividade: </span></td>
										<td><span  class="label-input100"> {{ ind.produtividade }}</span></td>
									</tr>
								</table>

						{% endfor %}
					</div>

				<div class="container-contact100-form-btn">
					<button class="contact100-form-btn">
						<span>
							COMPARAR..
							<i class="fa fa-long-arrow-right m-l-7" aria-hidden="true"></i>
						</span>
					</button>
				</div>
			</form>
		</div>
	</div>



<!--===============================================================================================-->
	<script src=' {% static "vendor/jquery/jquery-3.2.1.min.js" %} '></script>
<!--===============================================================================================-->
	<script src=' {% static "vendor/animsition/js/animsition.min.js" %} '></script>
<!--===============================================================================================-->
	<script src=' {% static "vendor/bootstrap/js/popper.js" %} '></script>
	<script src=' {% static "vendor/bootstrap/js/bootstrap.min.js" %} '></script>
<!--===============================================================================================-->
	<script src=' {% static "vendor/select2/select2.min.js" %} '></script>
	<script>
		$(".js-select2").each(function(){
			$(this).select2({
				minimumResultsForSearch: 20,
				dropdownParent: $(this).next('.dropDownSelect2')
			});


			$(".js-select2").each(function(){
				$(this).on('select2:close', function (e){
					if($(this).val() == "Please chooses") {
						$('.js-show-service').slideUp();
					}
					else {
						$('.js-show-service').slideUp();
						$('.js-show-service').slideDown();
					}
				});
			});
		})
	</script>
<!--===============================================================================================-->
	<script src=' {% static "vendor/daterangepicker/moment.min.js" %} '></script>
	<script src=' {% static "vendor/daterangepicker/daterangepicker.js" %} '></script>
<!--===============================================================================================-->
	<script src=' {% static "vendor/countdowntime/countdowntime.js" %} '></script>
<!--===============================================================================================-->
	<script src=' {% static "vendor/noui/nouislider.min.js" %} '></script>
	<script>
	    var filterBar = document.getElementById('filter-bar');

	    noUiSlider.create(filterBar, {
	        start: [ 1500, 3900 ],
	        connect: true,
	        range: {
	            'min': 1500,
	            'max': 7500
	        }
	    });

	    var skipValues = [
	    document.getElementById('value-lower'),
	    document.getElementById('value-upper')
	    ];

	    filterBar.noUiSlider.on('update', function( values, handle ) {
	        skipValues[handle].innerHTML = Math.round(values[handle]);
	        $('.contact100-form-range-value input[name="from-value"]').val($('#value-lower').html());
	        $('.contact100-form-range-value input[name="to-value"]').val($('#value-upper').html());
	    });
	</script>
<!--===============================================================================================-->
	<script src=' {% static "js/main.js" %} '></script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>

</body>
</html>